### PR TITLE
removed the automatic adding of the wildcard.

### PR DESCRIPTION
**Pull request by maikvandergaag**
Let end user make the decision, this way there is also searched in sub folders.

### CODE REVIEW

**Comment by sam-cogan** [comment]
Hi, thanks for the pull request!
I'm not sure I am clear on the reasoning around this however. The wildcard here only gets added if you pass in a folder as the "templateLocation" parameter, not a file. If you had passed in a folder only, what else would you want to do other than scanning all files in the folder?

Feel free to point out if I am missing something obvious!

**Comment by maikvandergaag** [comment]
Hi Sam,

I would also like to scan all sub folders in the folder that is supplied.

I normally use this structure for my arm templates:

src\arm-templates\lighthouse
src\arm-templates\monitoring

I want to configure the extension to the arm templates folder and then also scan the sub folders.

Groetjes,

Maik van der Gaag
________________________________
Van: Sam Cogan <notifications@github.com>
Verzonden: Saturday, April 4, 2020 5:32:39 PM
Aan: sam-cogan/arm-ttk-extension <arm-ttk-extension@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [sam-cogan/arm-ttk-extension] removed the automatic adding of the wildcard. (#9)


Hi, thanks for the pull request!
I'm not sure I am clear on the reasoning around this however. The wildcard here only gets added if you pass in a folder as the "templateLocation" parameter, not a file. If you had passed in a folder only, what else would you want to do other than scanning all files in the folder?

Feel free to point out if I am missing something obvious!

**Comment by sam-cogan** [comment]
This should work now. Changes we added last week mean that if you specify a folder it will scan all folders underneath that for .json files

**Comment by maikvandergaag** [comment]
That did not work for me, tested it today. The fix I added worked for me

Groetjes,

Maik van der Gaag
________________________________
Van: Sam Cogan <notifications@github.com>
Verzonden: Saturday, April 4, 2020 6:36:18 PM
Aan: sam-cogan/arm-ttk-extension <arm-ttk-extension@noreply.github.com>
CC: Maik van der Gaag <maik@familie-vandergaag.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [sam-cogan/arm-ttk-extension] removed the automatic adding of the wildcard. (#9)


This should work now. Changes we added last week mean that if you specify a folder it will scan all folders underneath that for .json files

**Comment by sam-cogan** [comment]
I've just tested the existing extension in the marketplace against a folder with multiple nested templates and all works as expected.
Can you screenshot your pipeline or manual test please so I can see what it looks like?

**Comment by maikvandergaag** [comment]
Hi Sam, do not have the configuration at this time, can set it up if needed could you maybe share your configuration? I have tried a lot of options.

**Comment by sam-cogan** [comment]
@maikvandergaag all I did was checkout my Demos repo (https://github.com/sam-cogan/Demos) which is full of ARM templates, then run the extension against that. This successfully tested all templates under that root folder, which has multiple layers of nesting.

**Comment by sam-cogan** [comment]
As far as I can tell the extension already works in the way described in this pull request. Feel free to re-open if you would like to add more details.

**Comment by maikvandergaag** [comment]
Hi Sam,

Did some testing again today, but on some servers it is still not working. To give you an idea:

I have this configuration at a client and it works:
 - task: RunARMTTKTests@1
    displayName: "Validate - ARM Templates"
    inputs:
      templatelocation: '$(Build.Repository.LocalPath)\src\arm-templates'
      resultLocation: "$(Build.Repository.LocalPath)"

I have this configuration on my own devops environment and it does not work
- task: RunARMTTKTests@1
    displayName: "Validate - ARM Templates"
    inputs:
      templatelocation: '$(Build.Repository.LocalPath)\arm'
      resultLocation: "$(Build.Repository.LocalPath)"


If I run the code locally of the method: Invoke-TTK it also has the issue with the '\*' that  is included. In my opinion this should not be required when doing a recursive search.

**Comment by sam-cogan** [comment]
I could really use an example set of files where this is exhibiting the issue you are seeing. So far all my testing has shown it working as expected. Can you replicate the issue with a non-confidential set of templates?

**Pull request closed without merging**
