### PR TITLE
updated IDs should be derived from resourceIDs to armttk commitID 7d6…

### PR DESCRIPTION
**Pull request by LeonB87**
Updated IDs-Should-Be-Derived-From-ResourceIDs.test.ps1 to latest version from ARM-TTK as this caused our pipeline to fail.

### CODE REVIEW

**Comment by LeonB87** [comment]
Hi @sam-cogan , Is updating the arm-ttk extension as easy as updating the testcases ps1 files from the original arm-ttk file? If so, I can create a new PR with all new test files.

I've now only added one as this is causing our pipeline to fail.

**Comment by sam-cogan** [comment]
Hey Leon,
The test actually get updated each time I release the extension so all that should be needed is to release a new version, I'll look to do that this weekend. 

I should probably remove the copy in the repo.

**Comment by sam-cogan** [comment]
@LeonB87  you should see a new version of the extension appear soon which should have all tests updated including this one. let me know if that works as expected and we can close this.

**Comment by LeonB87** [comment]
@sam-cogan This did the trick Sam, thank-you! Regards, Léon

**Pull request closed without merging**
